import Navbar from '@/components/Navbar'

import './globals.css'
import type { Metadata } from 'next'
import { Dekko } from 'next/font/google'

const dekko =  Dekko({
  weight: '400', // Puedes ajustar estas opciones según tus necesidades
  style: 'normal',
  display: 'swap', 
  subsets: ['latin'],// Por ejemplo, aquí se define 'display' como 'swap'
  // Agrega otras opciones según sea necesario
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={dekko.className}>
        <Navbar/>
        {children}
        

      </body>
    </html>
  )
}
